require: rubocop-rspec

AllCops:
  RSpec:
    Patterns:
    - '.+'

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/Documentation:
  Enabled: false